<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="style.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
</head>
<body>
  <?php
    if (session_status() == PHP_SESSION_NONE) {
        session_set_cookie_params(3600*24*365*10); //session-cookien varar i 10 år.
        session_start();
    }
    if(isset($_SESSION['loggedIn'])){
  ?>
  <template id="loggedIn" data-userid="<?php echo $_SESSION['userID']; ?>"></template>
  <?php
    }  ?>
  <template id="loginFormTemplate">
    <h2 class="registerLogin">Logga in</h2>
    <form id="loginForm">
      <label for="username">Användarnamn:</label> <br>
      <input type="text" name="username" id="username">
<br>  
      <label for="password">Lösenord:</label> <br>
      <input type="password" name="password" id="password">
<br> <br>
      <button type="submit" class="button">Logga in</button>
    </form>
  </template>

  <template id="registerFormTemplate">
    <h2 class="registerLogin">Registrera en ny användare</h2>
    <form id="registerForm">
      <label for="username">Användarnamn:</label> <br>
      <input type="text" name="username" id="username">
<br>
      <label for="password">Lösenord:</label> <br>
      <input type="password" name="password" id="password">
<br> <br>
      <button type="submit" class="button">Registrera</button>
    </form>
  </template> 

  <template id="loginErrorTemplate">
  <div class="alert alert-danger" role="alert">
    Något blev fel med inloggningen
    </div>
  </template>

  <template id="registerErrorTemplate">
    <div class="alert alert-danger" role="alert">
    Användarnamnet finns redan
    </div>
  </template>

 
  
  <template id="logoutErrorTemplate">
  <div class="alert alert-danger" role="alert">
    Något blev fel med utloggningen
    </div>
  </template>
  
  <template id="logoutSuccessTemplate">
  <div class="alert alert-info" role="alert">
    Du är utloggad
</div>
  </template>

  <template id="loggedInNavTemplate">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a  href="#" id="btn-journal" class="navbar-brand home-link">Journal</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a  href="#" class="nav-link home-link">Hem</a>
          </li>
          <li class="nav-item">
            <a  href="#" class="nav-link my-entries-link">Mina inlägg</a>
          </li>
          <li class="nav-item">
            <a  href="#" class="nav-link userlist-link">Se användare</a>
          </li>
          <li class="nav-item">
            <a  href="#" class="nav-link post-entry-link">Skriv inlägg</a>
          </li>
          <li class="nav-item">
            <a  href="#" id="logout-btn" class="nav-link logout-link btn btn-primary">Logga ut</a>
          </li>
        </ul>
      </div>
    </nav>
  </template>

  <template id="loggedOutNavTemplate">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <a href="#" id="btn-journal" class="navbar-brand home-link">Journal</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a href="#" class="nav-link home-link">Hem</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link register-link">Registrera dig</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link login-link">Logga in</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link userlist-link">Se användare</a>
          </li>
        </ul>
      </div>
    </nav>
  </template>
  
  <template id="greetingTemplate">
    <h2>Välkommen till Assbook</h2>
    <p>🍑I framtiden kommer du bara kunna se bilder på rumpor här men innan dess kommer det gå att posta inlägg🍑</p>
  </template>

  <template id="greetingNewUserTemplate">
    <h2 class="welcome">Välkommen!</h2>
    <h3 class="loginNext">Logga in med dina nya användaruppgifter</h3>
    <p class="alert alert-success" role="alert">Användaren har nu skapats</p>
  </template>

  <template id="commentsTemplate">
   <p>🍑Greetings rumpdyrkare! Här kan du kommentera🍑</p>
  </template>

  <template id="commentFormTemplate">
    <h2>Kommentera inlägget</h2>
    <form id="commentForm">
      <input type="text" name="content">
      <button type="submit">Skicka</button>
    </form>
  </template>

  <template id="entrySummaryTemplate">
    <h2 data-templatemark="title">Titel:</h2>
  </template>

  <template id="entryTemplate">
    <h2>Titel:</h2>
    <p>Innehåll:</p>
  </template>

  <template id="entryErrorTemplate">
  <div class="alert alert-danger" role="alert">
   Inläggen går ej att visa
</div>
  </template>

  <template id="entrySummaryErrorTemplate">
  <div class="alert alert-danger" role="alert">
  Summerade inlägget går ej att visa
</div>
  </template>


 <template id="entriesErrorTemplate">
 <div class="alert alert-danger" role="alert">
  Det finns inga inlägg här
</div>
 </template>

 <!-- Titel och content ska läggas här -->
 <template id="TitelAndContentTemplate">
    <h1>Titel och innehåll</h1>
 </template>

 <template id="CreateNewEntryTemplate">
 <h2 class='title'>Skapa ett inlägg</h2>
 <form id="newEntryForm">
  <div class="form-group">
    <label for="entrytitle">Titel:</label>
    <input name="title" type="text" class="form-control" id="entrytitle" placeholder="Titel">
  </div>
  <div class="form-group">
    <label for="entrycontent"></label>
    <textarea name="content" class="form-control" id="entrycontent" rows="20" col="10" placeholder="Skriv ditt inlägg här"></textarea>
  </div>
  <button class="btn btn-primary">Skicka</button>
</form>
 </template>

 <template id="errorNewEntryTamplate">
 <div class="alert alert-danger" role="alert">
  Inlägget skapades ej
</div>
 </template>

 

 

  <div id="nav"></div>
  <div class="container">
  
    <header>
      <h1><?= $title ?></h1>
    </header>
    <main>
      <!-- Allt som skrivs här hamnar i main.js -->
    </main>
  </div>
 

  <script type="text/javascript" src="main.js"></script>
</body>
</html>
