<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>

  <template id="loginFormTemplate">
    <h2>Log in</h2>
    <form id="loginForm">
      <label for="username">Username:</label>
      <input type="text" name="username" id="username">

      <label for="password">Password:</label>
      <input type="password" name="password" id="password">

      <button type="submit">Log in</button>
    </form>
  </template>

  <template id="registerFormTemplate">
    <h2>Register new user</h2>
    <form id="registerForm">
      <label for="username">Username:</label>
      <input type="text" name="username" id="username">

      <label for="password">Password:</label>
      <input type="password" name="password" id="password">

      <button type="submit">Register</button>
    </form>
  </template> 

  <template id="loggedInNavTemplate">
    
  </template>

  <template id="loggedOutNavTemplate">
    
  </template>

  <div class="container">
    <header>
      <h1><?= $title ?></h1>
    </header>
    <main>
      <!-- INNEHÅLL -->
    </main>
  </div>

  <script type="text/javascript" src="main.js"></script>
</body>
</html>
