<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?=$title?></title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
  <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
  <?php
    if(isset($_SESSION['loggedIn'])){
  ?>
  <template id="loggedIn"></template>
  <?php
    }
  ?>
  <template id="loginFormTemplate">
    <h2>Log in</h2>
    <form id="loginForm">
      <label for="username">Username:</label>
      <input type="text" name="username" id="username">

      <label for="password">Password:</label>
      <input type="password" name="password" id="password">

      <button type="submit">Log in</button>
    </form>
  </template>

  <template id="registerFormTemplate">
    <h2>Register new user</h2>
    <form id="registerForm">
      <label for="username">Username:</label>
      <input type="text" name="username" id="username">

      <label for="password">Password:</label>
      <input type="password" name="password" id="password">

      <button type="submit">Register</button>
    </form>
  </template> 

  <template id="loginErrorTemplate">
    <p>Något blev fel med inloggningen :/</p>
  </template>

  <template id="registerErrorTemplate">
    <p>Något blev fel med registreringen :/</p>
  </template>
  
  <template id="logoutErrorTemplate">
    <p>Något blev fel med utloggningen :/</p>
  </template>
  
  <template id="logoutSuccessTemplate">
    <p>Du är utloggad</p>
  </template>

  <template id="loggedInNavTemplate">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <span class="navbar-brand home-link">Journal</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <span class="nav-link home-link">Hem</span>
          </li>
          <li class="nav-item">
            <span class="nav-link my-entries-link">Mina inlägg</span>
          </li>
          <li class="nav-item">
            <span class="nav-link userlist-link">Se användare</span>
          </li>
          <li class="nav-item">
            <span class="nav-link post-entry-link">Skriv inlägg</span>
          </li>
          <li class="nav-item">
            <span class="nav-link logout-link btn btn-primary">Logga ut</span>
          </li>
        </ul>
      </div>
    </nav>
  </template>

  <template id="loggedOutNavTemplate">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
      <span class="navbar-brand home-link">Journal</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <span class="nav-link home-link">Hem</span>
          </li>
          <li class="nav-item">
            <span class="nav-link register-link">Registrera dig</span>
          </li>
          <li class="nav-item">
            <span class="nav-link login-link">Logga in</span>
          </li>
          <li class="nav-item">
            <span class="nav-link userlist-link">Se användare</span>
          </li>
        </ul>
      </div>
    </nav>
  </template>
  
  <template id="greetingTemplate">
    <h2>Välkommen till Assbook</h2>
    <p>🍑I framtiden kommer du bara kunna se bilder på rumpor här men innan dess kommer det gå att posta inlägg🍑</p>
  </template>

  <template id="greetingNewUserTemplate">
    <h2>Välkommen till Assbook</h2>
    <p>🍑Greetings nya Användare! Här dyrkar vi rumpor🍑</p>
  </template>

  <template id="entrySummeryTemplate">
    <h1 class="entrytitle">test</h1>
  </template>

  <div id="nav"></div>
  <div class="container">
  
    <header>
      <h1><?= $title ?></h1>
    </header>
    <main>
      <!-- INNEHÅLL -->
    </main>
  </div>

  <script type="text/javascript" src="main.js"></script>
</body>
</html>
